#!/usr/bin/env bash
# Configures /etc/hosts to change localhost and facebook.com resolution

HOSTS_FILE="/etc/hosts"

sed -i '/[[:space:]]localhost\( \|$\)/d' "$HOSTS_FILE"
sed -i '/[[:space:]]facebook\.com\( \|$\)/d' "$HOSTS_FILE"

echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"
