#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2

HOSTS_FILE="/etc/hosts"

sed -i '/^127\.0\.0\.1[[:space:]]\+localhost/d' "$HOSTS_FILE"
sed -i '/[[:space:]]localhost/d' "$HOSTS_FILE"

echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"
